### PR TITLE
Added option to disable hiding behavior

### PR DESCRIPTION
**Pull request by LucasTavaresA**
format-spec its a builtin

### CODE REVIEW

**Comment by manateelazycat** [comment]
@LucasTavaresA Why add this option? One reason why users use awesome-tray is to hide mode-line.

**Comment by LucasTavaresA** [comment]
> @LucasTavaresA Why add this option? One reason why users use awesome-tray is to hide mode-line.

well you can always just set mode-line-format to nil, i personally prefer doing that

**Comment by manateelazycat** [comment]
> > @LucasTavaresA Why add this option? One reason why users use awesome-tray is to hide mode-line.
> 
> well you can always just set mode-line-format to nil, i personally prefer doing that

So, if we disable this option, then blank mode-line coexist with awesome-tray?

**Comment by LucasTavaresA** [comment]
> > > @LucasTavaresA Why add this option? One reason why users use awesome-tray is to hide mode-line.
> > 
> > 
> > well you can always just set mode-line-format to nil, i personally prefer doing that
> 
> So, if we disable this option, then blank mode-line coexist with awesome-tray?

i thought the active indicator was a feature, yes you do have to set this option and the format to nil to actually disable the mode-line

**Comment by manateelazycat** [comment]
If we use `(setq mode-line-format nil)`, mode-line will hide completely, but we also lost active status, user don't know which window is active.

If we found better way to show active window status, I perfer use `(setq mode-line-format nil)` to hide mode-line.

**Comment by LucasTavaresA** [comment]
> If we use `(setq mode-line-format nil)`, mode-line will hide completely, but we also lost active status, user don't know which window is active.
> 
> If we find better way to show active window status, I perfer use `(setq mode-line-format nil)` to hide mode-line.

im using auto-dim-other-buffers that changes inactive buffers background so i didn't thought about that
but my proposal its to give the user the option to personalize this behavior by himself as it makes it difficult to actually disable to mode-line completely when enabled

**Comment by manateelazycat** [comment]
> 

I use EAF in Emacs a lot, auto-dim-other-buffers and cursor-in-non-selected-windows not work, because EAF xreparent Qt/Web window upon Emacs frame, no cursor or difference background feature in Qt/Web window.

**Comment by LucasTavaresA** [comment]
> > 
> 
> I use EAF in Emacs a lot, auto-dim-other-buffers and cursor-in-non-selected-windows not work, because EAF xreparent Qt/Web window upon Emacs frame, no cursor or difference background feature in Qt/Web window.

well not much else to say the old behavior is preferred in this patch, the decision is all yours

**Comment by manateelazycat** [comment]
I know why this option need add, this patch looks fine.

Haven't perfect way to show active window status after hide mode-line completely.

**Pull request merged**
