### PR TITLE
add pdf-view-page module

### PR DESCRIPTION
**Pull request by wtding1998**

### CODE REVIEW

**Comment by manateelazycat** [comment]
We have print page number at bottom-right of page page, did you need this?

**Comment by wtding1998** [comment]
Sorry. Do you mean we don't need this module because most pdf files already display page number at bottom? Or is there any other way to find the page number?

**Comment by manateelazycat** [comment]
2022-05-14 20-58-39 的屏幕截图

In eaf-pdf-viewer , we will display currentPage/totalPage at bottom-right, so we don't need show agian in awesome-tray.

**Comment by wtding1998** [comment]
Thank you for your detailed response and I get your point now. But I usually use [pdf-tools](https://github.com/politza/pdf-tools) to view pdf files in emacs, which displays page number in modeline by default. That's why I want to add this module.

Maybe I should give your package a try. Thanks again!

**Comment by manateelazycat** [comment]
@wtding1998 eaf-pdf-viewer is fastest pdf viewer for Emacs.

Anyway thanks for patch.  ;)

**Comment by manateelazycat** [comment]
Patch can merge for pdf-tools even I just use eaf-pdf-viewer.

**Comment by wtding1998** [comment]
eaf-pdf-viewer looks cool. Thank you so much.

**Pull request merged**
